import { readRepoFile } from '@/lib/stockbook';
import { parseHoldingsTable } from '@/lib/holdings';
import {
  isNewsWriteIntent,
  parseNewsDateFromQuery,
  readNewsSummaryFile,
  writeNewsSummary,
  newsWebPath,
} from '@/lib/news-write';
import fs from 'fs/promises';
import path from 'path';
import { getUserPaths } from '@/lib/tenant';
import type { AgentQueryContext, AgentQueryResult } from './framework-agent';

async function writeAgentInbox(
  tenantId: string,
  query: string,
  answer: string
): Promise<void> {
  const dir = path.join(getUserPaths(tenantId).portfolioDir, '../agent-inbox');
  await fs.mkdir(dir, { recursive: true });
  const body = `# Web Ask Agent — News run

**Updated:** ${new Date().toISOString()}

## Question

${query}

## Answer

${answer}
`;
  await fs.writeFile(path.join(dir, 'last-query.md'), body, 'utf8');
}

function clip(text: string, max = 8000): string {
  if (text.length <= max) return text;
  return text.slice(0, max) + '\n\n… [truncated]';
}

function istNowParts(now = new Date()): { date: string; time: string } {
  const ist = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
  const y = ist.getFullYear();
  const m = String(ist.getMonth() + 1).padStart(2, '0');
  const d = String(ist.getDate()).padStart(2, '0');
  const hh = String(ist.getHours()).padStart(2, '0');
  const mm = String(ist.getMinutes()).padStart(2, '0');
  return { date: `${y}-${m}-${d}`, time: `${hh}:${mm}` };
}

async function callGemini(system: string, userPrompt: string): Promise<string | null> {
  const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  if (!apiKey) return null;

  const model = process.env.GEMINI_MODEL ?? 'gemini-3.6-flash';
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: system }] },
      contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
      generationConfig: { temperature: 0.25, maxOutputTokens: 8192 },
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Gemini API error: ${res.status} ${err.slice(0, 200)}`);
  }

  const json = await res.json();
  return json?.candidates?.[0]?.content?.parts?.[0]?.text ?? null;
}

function buildLocalNewsSummary(
  date: string,
  holdingsLines: string[],
  userQuery: string,
  priorSummary: string | null
): string {
  const { time } = istNowParts();
  const weekday = new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', {
    weekday: 'long',
    timeZone: 'Asia/Kolkata',
  });

  return `# News summary — ${date}

**Date checked:** ${date} (${weekday})  
**Search window:** ${date} **00:01 – ${time} IST** (partial — web agent run)  
**Buckets scanned:** A Pre-market · B Session · C Post-close — **UNVERIFIED** (add Gemini key + live search for full run)  
**Sources:** User query + framework holdings list · refresh with CNBC-TV18 · Moneycontrol · ET · NDTV Profit

---

## Portfolio impact — holdings (primary table)

| Stock name | News | Impact | Type | Structural vs temporary | Action implication |
|------------|------|:------:|------|-------------------------|-------------------|
| *Pending* | Run full SEARCH-WORKFLOW stock-wise loop (50 holdings) | — | UNVERIFIED | — | HOLD pending refresh |

*Framework requires stock-by-stock search on four primary outlets — this stub was created because write path was blocked; content must be enriched.*

---

## Macro & policy

| Item | Reading | Type |
|------|---------|------|
| User request | ${userQuery.replace(/\|/g, '/').slice(0, 200)} | FACT |

---

## Geopolitical

| Situation | Status | Direction | India transmission |
|-----------|--------|-----------|-------------------|
| — | UNVERIFIED | — | Add live search |

---

## Triggers — what would change the view

- Full daily search completed per \`News/SEARCH-WORKFLOW.md\`
- Material headline on any portfolio name
- RBI / crude / FII flow shift

---

## Agent note

${priorSummary ? '*Prior day summary loaded for carry-forward context only.*' : '*No prior day summary found.*'}

**Holdings in scope (${holdingsLines.length}):**

${holdingsLines.slice(0, 20).map((l) => `- ${l}`).join('\n')}
${holdingsLines.length > 20 ? `\n… +${holdingsLines.length - 20} more` : ''}

*Generated by web Ask Agent (framework-local). Re-run with Gemini for full SEARCH-WORKFLOW synthesis.*
`;
}

export interface NewsQueryResult extends AgentQueryResult {
  newsDate?: string;
  newsFilePath?: string;
  newsWebPath?: string;
}

export function shouldRunNewsAgent(query: string): boolean {
  return isNewsWriteIntent(query);
}

export async function runNewsFrameworkQuery(
  query: string,
  context: AgentQueryContext
): Promise<NewsQueryResult> {
  const targetDate =
    parseNewsDateFromQuery(query) ?? istNowParts().date;

  const [newsRules, searchWorkflow, priorSummary] = await Promise.all([
    readRepoFile('News/AGENT-RULES.md').catch(() => ''),
    readRepoFile('News/SEARCH-WORKFLOW.md').catch(() => ''),
    readNewsSummaryFile(targetDate),
  ]);

  let holdingsBlock = 'No holdings imported.';
  let holdingsLines: string[] = [];
  try {
    const rows = await parseHoldingsTable(context.tenantId);
    holdingsLines = rows.map(
      (r) => `${r.ticker} / ${r.company} (${r.holdingsSector})`
    );
    holdingsBlock = holdingsLines.join('\n');
  } catch {
    /* empty */
  }

  const { date: todayIst, time: timeIst } = istNowParts();
  const isPartial = targetDate === todayIst;

  const system = `# Role — Daily News Framework Agent (web)

You write **News/YYYY-MM/YYYY-MM-DD/summary.md** for the India Stock Investment Agent.

**NOT generic market commentary.** Follow News/AGENT-RULES.md and News/SEARCH-WORKFLOW.md exactly.

Mandatory sections in output (markdown only, no preamble):
1. Title: # News summary — YYYY-MM-DD
2. Header: Date checked, Search window, Buckets scanned, Sources (four primary outlets)
3. ## Portfolio impact — holdings (primary table) — columns: Stock name | News | Impact | Type | Structural vs temporary | Action implication
4. ## Macro & policy
5. ## Geopolitical
6. ## Sector surplus band (optional)
7. ## Triggers — what would change the view

Rules:
- Label FACT | MANAGEMENT CLAIM | HYPOTHESIS | OUR ASSUMPTION | UNVERIFIED
- Search window: ${targetDate} 00:01 – ${isPartial ? timeIst : '23:59'} IST (${isPartial ? 'partial' : 'full calendar day target'})
- Stock-wise: address holdings from user portfolio — do not use sector proxy alone
- If you lack live headlines, state UNVERIFIED and use user-provided facts from their message
- Never invent court dates or penalty amounts

## AGENT-RULES excerpt
${clip(newsRules, 5000)}

## SEARCH-WORKFLOW excerpt
${clip(searchWorkflow, 4000)}
`;

  const userPrompt = `Write the complete **summary.md** for date **${targetDate}**.

**User request:** ${query}

**Portfolio holdings (${holdingsLines.length}):**
${holdingsBlock || 'None — macro-only summary'}

${priorSummary ? `**Existing summary for ${targetDate} (merge/update, do not duplicate blindly):**\n${clip(priorSummary, 3000)}` : '**No existing summary for this date — create fresh.**'}

${query.includes('\n') ? `\n**User-provided headlines/content:**\n${query}` : ''}

Return ONLY the markdown file content starting with # News summary — ${targetDate}`;

  let summaryMd: string;
  let mode: AgentQueryResult['mode'] = 'framework-local';
  let model: string | undefined;

  try {
    const gemini = await callGemini(system, userPrompt);
    if (gemini && gemini.includes('# News summary')) {
      summaryMd = gemini.trim();
      mode = 'gemini';
      model = process.env.GEMINI_MODEL ?? 'gemini-3.6-flash';
    } else {
      summaryMd = buildLocalNewsSummary(targetDate, holdingsLines, query, priorSummary);
    }
  } catch {
    summaryMd = buildLocalNewsSummary(targetDate, holdingsLines, query, priorSummary);
  }

  const writtenPath = await writeNewsSummary(targetDate, summaryMd);
  const webPath = newsWebPath(targetDate);

  const answerBody = `## Framework lens

Applied **News/AGENT-RULES.md** + **SEARCH-WORKFLOW.md** — daily summary write (not generic chat).

1. Parsed target date: **${targetDate}**
2. Loaded portfolio (${holdingsLines.length} holdings) for stock-wise impact table
3. Wrote framework \`summary.md\` to repo News archive
4. Web News tab updated — browse Year → Month → Date

---

## Context used

- **News date:** ${targetDate}
- **File:** \`News/${targetDate.slice(0, 7)}/${targetDate}/summary.md\`
- **Prior summary same date:** ${priorSummary ? 'Yes — merged/updated' : 'No — created new'}
- **Mode:** ${mode}${model ? ` (${model})` : ' (local template — add Gemini key for full synthesis)'}

---

## Verdict

**News summary saved** — review Portfolio impact table; run stock-wise SEARCH-WORKFLOW refresh if buckets show UNVERIFIED.

---

## View in app

Open **[News → ${targetDate}](${webPath})** or the **News** tab (September ${parseInt(targetDate.slice(5, 7), 10)} → ${parseInt(targetDate.slice(8, 10), 10)}).

---

## Next steps (framework)

1. Update \`News/TICKER-INDEX.md\` with key tickers from this summary
2. Refresh affected StockBook \`summary-analysis.md\` if SIP pace / current value changes
3. Re-run end-of-day with **full** window 00:01–23:59 IST if this was a partial run

---

*Framework precedence: News AGENT-RULES → SEARCH-WORKFLOW → Holdings → Not chat-only memory.*
`;

  await writeAgentInbox(context.tenantId, query, answerBody);

  return {
    answer: answerBody,
    mode,
    model,
    newsDate: targetDate,
    newsFilePath: writtenPath,
    newsWebPath: webPath,
  };
}
