import fs from 'fs/promises';
import path from 'path';
import { randomUUID } from 'crypto';
import { getUserPaths, assertSafeTenantId } from './tenant';
import { writeTenantIndexFile, writeTenantMarkdownFile } from './tenant-disk-persist';
import { groupByYearMonthDate, type DateYearGroup } from './date-history-group';
import { createClientIfConfigured } from './supabase/server';
import {
  isMissingTableError,
  isSupabaseTableUnavailable,
  markSupabaseTableUnavailable,
  warnMissingTableOnce,
} from './supabase/schema-errors';
import type { BusinessQualityResult } from './business-quality-moat';
import { findFullAnalysisByChildModuleId } from './full-analysis-child-lookup';

export interface BusinessQualityRecord {
  id: string;
  createdAt: string;
  ticker: string;
  stockName: string;
  sector: string;
  cmp: number | null;
  businessQualityScore10: number;
  verdict: string;
  report: string;
  analysis: BusinessQualityResult;
}

interface BusinessQualityIndexFile {
  version: 1;
  entries: BusinessQualityRecord[];
}

interface BusinessQualityHistoryRow {
  id: string;
  user_id: string;
  ticker: string;
  stock_name: string;
  sector: string;
  cmp: number | null;
  business_quality_score_10: number;
  verdict: string;
  report: string;
  analysis: BusinessQualityResult;
  created_at: string;
}

const BUSINESS_QUALITY_HISTORY_TABLE = 'business_quality_history';

function businessQualityDir(tenantId: string): string {
  return path.join(getUserPaths(tenantId).portfolioDir, '../stock-calculator/business-quality');
}

function indexPath(tenantId: string): string {
  return path.join(businessQualityDir(tenantId), 'index.json');
}

async function readIndex(tenantId: string): Promise<BusinessQualityIndexFile> {
  try {
    const raw = await fs.readFile(indexPath(tenantId), 'utf8');
    const parsed = JSON.parse(raw) as BusinessQualityIndexFile;
    if (parsed?.version === 1 && Array.isArray(parsed.entries)) return parsed;
  } catch {
    /* new */
  }
  return { version: 1, entries: [] };
}

async function writeIndex(tenantId: string, data: BusinessQualityIndexFile): Promise<void> {
  await writeTenantIndexFile(indexPath(tenantId), data);
}

export function formatBusinessQualityReport(analysis: BusinessQualityResult): string {
  const lines: string[] = [
    `# Business Quality & Moat — ${analysis.stockName} (${analysis.ticker})`,
    '',
    `**Sector:** ${analysis.sector}`,
    `**CMP:** ${analysis.cmp != null ? `₹${analysis.cmp.toLocaleString('en-IN')}` : '—'} (${analysis.cmpSource})`,
    `**Business Quality:** ${analysis.businessQualityScore10}/10`,
    `**Verdict:** ${analysis.verdict}`,
    '',
    `> ${analysis.coreQuestion}`,
    '',
    '## Scorecard',
    '',
    '| Pillar | Score | Signal | Headline |',
    '|--------|------:|--------|----------|',
    ...analysis.pillars.map(
      (p) =>
        `| ${p.number}. ${p.title} | ${p.score10 ?? '—'}/10 | ${p.signal} | ${p.headline.replace(/\|/g, '/')} |`
    ),
    '',
  ];

  if (analysis.highlights.length > 0) {
    lines.push(
      '## Factor highlights',
      '',
      '| Factor | Assessment | Signal |',
      '|--------|------------|--------|',
      ...analysis.highlights.map((h) => `| ${h.factor} | ${h.assessment} | ${h.signal} |`),
      ''
    );
  }

  for (const p of analysis.pillars) {
    if (p.factors.length === 0) continue;
    lines.push(`## ${p.number}. ${p.title}`, '');
    lines.push('| Factor | Assessment | Signal | Evidence |');
    lines.push('|--------|------------|--------|----------|');
    lines.push(
      ...p.factors.map(
        (f) => `| ${f.label} | ${f.assessment} | ${f.signal} | ${f.evidence} |`
      )
    );
    lines.push('');
  }

  if (analysis.notTenReasons.length > 0) {
    lines.push('## Why not 10/10?', '');
    for (const r of analysis.notTenReasons) {
      lines.push(`- ${r}`);
    }
    lines.push('');
  }

  lines.push('---', '', '_Generated by Stock Calculator — Business Quality & Moat. Not investment advice._');
  return lines.join('\n');
}

export function analysisToRecord(analysis: BusinessQualityResult, id?: string): BusinessQualityRecord {
  const recordId = id ?? randomUUID();
  return {
    id: recordId,
    createdAt: new Date().toISOString(),
    ticker: analysis.ticker,
    stockName: analysis.stockName,
    sector: analysis.sector,
    cmp: analysis.cmp,
    businessQualityScore10: analysis.businessQualityScore10,
    verdict: analysis.verdict,
    report: formatBusinessQualityReport(analysis),
    analysis,
  };
}

function rowToRecord(row: BusinessQualityHistoryRow): BusinessQualityRecord {
  return {
    id: row.id,
    createdAt: row.created_at,
    ticker: row.ticker,
    stockName: row.stock_name,
    sector: row.sector,
    cmp: row.cmp != null ? Number(row.cmp) : null,
    businessQualityScore10: Number(row.business_quality_score_10),
    verdict: row.verdict,
    report: row.report,
    analysis: row.analysis,
  };
}

async function persistRecordToDisk(tenantId: string, record: BusinessQualityRecord): Promise<void> {
  const index = await readIndex(tenantId);
  const existing = index.entries.findIndex((e) => e.id === record.id);
  if (existing >= 0) index.entries[existing] = record;
  else index.entries.unshift(record);
  await writeIndex(tenantId, index);
  await writeTenantMarkdownFile(
    path.join(businessQualityDir(tenantId), `${record.id}.md`),
    record.report
  );
}

async function fetchAllFromSupabase(userId: string): Promise<BusinessQualityRecord[]> {
  if (isSupabaseTableUnavailable(BUSINESS_QUALITY_HISTORY_TABLE)) return [];
  const supabase = await createClientIfConfigured();
  if (!supabase) return [];

  const { data, error } = await supabase
    .from(BUSINESS_QUALITY_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(BUSINESS_QUALITY_HISTORY_TABLE);
      warnMissingTableOnce(BUSINESS_QUALITY_HISTORY_TABLE, '006_business_quality_history.sql');
      return [];
    }
    return [];
  }
  return (data as BusinessQualityHistoryRow[]).map(rowToRecord);
}

async function fetchOneFromSupabase(userId: string, id: string): Promise<BusinessQualityRecord | null> {
  if (isSupabaseTableUnavailable(BUSINESS_QUALITY_HISTORY_TABLE)) return null;
  const supabase = await createClientIfConfigured();
  if (!supabase) return null;

  const { data, error } = await supabase
    .from(BUSINESS_QUALITY_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .eq('id', id)
    .maybeSingle();

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(BUSINESS_QUALITY_HISTORY_TABLE);
      warnMissingTableOnce(BUSINESS_QUALITY_HISTORY_TABLE, '006_business_quality_history.sql');
    }
    return null;
  }
  if (!data) return null;
  return rowToRecord(data as BusinessQualityHistoryRow);
}

export interface SaveBusinessQualityInput {
  tenantId: string;
  userId: string;
  authMode: 'supabase' | 'cookie-dev';
  analysis: BusinessQualityResult;
}

export async function saveBusinessQualityRecord(
  input: SaveBusinessQualityInput
): Promise<BusinessQualityRecord> {
  assertSafeTenantId(input.tenantId);
  const record = analysisToRecord(input.analysis);
  await persistRecordToDisk(input.tenantId, record);

  if (input.authMode === 'supabase') {
    const supabase = await createClientIfConfigured();
    if (supabase && !isSupabaseTableUnavailable(BUSINESS_QUALITY_HISTORY_TABLE)) {
      const { error } = await supabase.from(BUSINESS_QUALITY_HISTORY_TABLE).insert({
        id: record.id,
        user_id: input.userId,
        ticker: record.ticker,
        stock_name: record.stockName,
        sector: record.sector,
        cmp: record.cmp,
        business_quality_score_10: record.businessQualityScore10,
        verdict: record.verdict,
        report: record.report,
        analysis: record.analysis,
      });
      if (error && isMissingTableError(error)) {
        markSupabaseTableUnavailable(BUSINESS_QUALITY_HISTORY_TABLE);
        warnMissingTableOnce(BUSINESS_QUALITY_HISTORY_TABLE, '006_business_quality_history.sql');
      }
    }
  }
  return record;
}

export async function listBusinessQualityRecords(
  tenantId: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<BusinessQualityRecord[]> {
  assertSafeTenantId(tenantId);
  let entries = (await readIndex(tenantId)).entries;

  if (entries.length === 0 && authMode === 'supabase' && userId) {
    const remote = await fetchAllFromSupabase(userId);
    if (remote.length > 0) {
      for (const record of remote) await persistRecordToDisk(tenantId, record);
      entries = remote;
    }
  }
  return entries.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getBusinessQualityRecord(
  tenantId: string,
  id: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<BusinessQualityRecord | null> {
  const local = (await readIndex(tenantId)).entries.find((e) => e.id === id);
  if (local) return local;

  if (authMode === 'supabase' && userId) {
    const remote = await fetchOneFromSupabase(userId, id);
    if (remote) {
      await persistRecordToDisk(tenantId, remote);
      return remote;
    }
  }

  const full = await findFullAnalysisByChildModuleId(tenantId, id, userId, authMode);
  if (full?.childIds.businessQuality === id) {
    return analysisToRecord(full.analysis.businessQuality, id);
  }

  return null;
}

export function groupBusinessQualityByDate(
  entries: BusinessQualityRecord[]
): DateYearGroup<BusinessQualityRecord>[] {
  return groupByYearMonthDate(entries, (e) => e.createdAt);
}
