/** Strip internal sections and framework jargon from markdown shown to end users. */

const INTERNAL_HEADINGS =
  /^## (Framework lens|Context used|FAQ write-back|Module verdicts \(synthesis\))[\s\S]*?(?=^## )/gm;

export function toInvestorFacingReport(markdown: string): string {
  let out = markdown;
  for (const re of [
    /^## Framework lens[\s\S]*?(?=^## )/m,
    /^## Context used[\s\S]*?(?=^## )/m,
  ]) {
    out = out.replace(re, '');
  }
  out = out.replace(INTERNAL_HEADINGS, '');
  out = out.replace(
    /\*Generated by Stock Analysis[\s\S]*$/m,
    '*Not investment advice.*'
  );
  out = out.replace(/\*Not investment advice\. Framework rules applied in background\.\*/g, '*Not investment advice.*');
  out = out.replace(/\*\*Mode:\*\* Basic Analysis[^\n]*\n/g, '');
  out = out.replace(/^# Framework report —/gm, '#');
  out = out.replace(/## Quotes lens/g, '## Quotes');
  out = out.replace(/## Actions \(framework\)/g, '## What to do');
  return out.trim();
}

function stripFrameworkJargon(text: string): string {
  return text
    .replace(/Framework-first[^\n]*\n/gi, '')
    .replace(/Framework \+ Gemini/gi, 'Enhanced synthesis')
    .replace(/Framework core/gi, 'Core analysis')
    .replace(/Framework verdict:/gi, 'Verdict:')
    .replace(/Framework-backed/gi, 'Disciplined')
    .replace(/Framework read/gi, 'Analysis read')
    .replace(/Framework-constrained/gi, 'Discipline-constrained')
    .replace(/Framework answer/gi, 'Answer')
    .replace(/framework possible band/gi, 'supported growth band')
    .replace(/framework possible/gi, 'supported')
    .replace(/framework synthesis/gi, 'discipline note')
    .replace(/framework room/gi, 'valuation room')
    .replace(/framework base EPS CAGR/gi, 'base EPS CAGR')
    .replace(/framework-supported/gi, 'discipline-supported')
    .replace(/India Stock Investment Framework/gi, 'investment discipline')
    .replace(/Investment framework/gi, 'Investment discipline')
    .replace(/Core framework/gi, 'Core valuation')
    .replace(/Abbreviations & Framework Terms/gi, 'Abbreviations & investment terms')
    .replace(/\*\*Mode:\*\*[^\n]*\n/g, '')
    .replace(/Framework precedence:[^\n]*\n/gi, '')
    .replace(/Not generic AI opinion\./gi, 'Not investment advice.');
}

/** Apply before returning any Ask Agent / journal answer. */
export function sanitizeUserFacingAnswer(markdown: string): string {
  const raw = (markdown ?? '').trim();
  if (!raw) {
    return (
      '**Could not load a full answer** — live market data or analysis modules failed on the server.\n\n' +
      '- Retry in a minute (during market hours)\n' +
      '- Open **Stock Analysis → Basic** for the same ticker\n' +
      '- On Vercel: ensure bundled StockBook sync ran at build; optional **GOOGLE_GENERATIVE_AI_API_KEY** helps general questions\n\n' +
      '*Not investment advice.*'
    );
  }
  const out = stripFrameworkJargon(toInvestorFacingReport(raw));
  if (!out.trim()) {
    return (
      '**Answer was empty after formatting** — retry or use **Stock Analysis → Basic** for this stock.\n\n' +
      '*Not investment advice.*'
    );
  }
  return out;
}

/** Short verdict lines (tags, one-liners) — no internal methodology wording. */
export function sanitizeVerdictLabel(text: string): string {
  return stripFrameworkJargon(text).replace(/\s+/g, ' ').trim();
}

/** Repo-relative paths shown in backticks — web shows conclusions only, not file map. */
const INTERNAL_PATH_BACKTICK =
  /`(?:\.cursor\/|StockBook\/|pccl-analysis\/|investor-wisdom\/|portfolio-analysis\/|stock-analysis\/|News\/|structural-threat-analysis\/|legal-threat-analysis\/|fraud-detection-analysis\/|dynamic-context-analysis\/|price-decline-analysis\/|stock-agent\.mdc|buy-decision-workflow\.md|personal-discipline\.md|[^`]*-FRAMEWORK\.md|[^`]*\/SKILL\.md)[^`]*`/gi;

function stripStockbookInternalRefs(markdown: string): string {
  let out = markdown;
  out = out.replace(/^Cross-ref:[^\n]*\n/gm, '');
  out = out.replace(/^> \*\*Cross-ref[^\n]*\n/gm, '');
  out = out.replace(/^See also `[^`]+`[^\n]*\n/gm, '');
  out = out.replace(/<!--[\s\S]*?-->/g, '');
  out = out.replace(INTERNAL_PATH_BACKTICK, '');
  out = out.replace(/`AGENT-RULES\.md`/gi, '');
  out = out.replace(/`holdings\.md`/gi, '');
  out = out.replace(/What is the framework action\?/gi, 'What is the recommended action?');
  out = out.replace(/\bframework action\b/gi, 'recommended action');
  out = out.replace(/\*\*Framework read \(past \+ forward\)\*\*/gi, '**Analysis read (past + forward)**');
  out = out.replace(/business \/ framework context/gi, 'business context');
  out = out.replace(/\bper framework\b/gi, 'per discipline');
  out = out.replace(/\bframework rank\b/gi, 'surplus rank');
  out = out.replace(/\bframework reason\b/gi, 'discipline reason');
  out = out.replace(/\bframework terms\b/gi, 'investment terms');
  out = out.replace(/\bTwo-axis framework\b/gi, 'Two-axis valuation');
  out = out.replace(/\bframework read\b/gi, 'analysis read');
  out = out.replace(/\n{3,}/g, '\n\n');
  return out.trim();
}

/**
 * StockBook tabs on the web — investor output only. Does not modify repo files or engine logic.
 */
export function sanitizeStockbookMarkdownForWeb(markdown: string): string {
  return stripStockbookInternalRefs(sanitizeUserFacingAnswer(markdown));
}

/** HTML stock reports (iframe) — text-only jargon strip; does not alter stored HTML. */
export function sanitizeStockbookHtmlForWeb(html: string): string {
  return stripStockbookInternalRefs(stripFrameworkJargon(html));
}

/**
 * Wisdom / quotes library on the web — quotes and themes only; agent meta hidden at render time.
 */
export function sanitizeWisdomMarkdownForWeb(markdown: string): string {
  let out = sanitizeStockbookMarkdownForWeb(markdown);
  out = out.replace(/^# Investor Wisdom — Quotes Library/m, '# Wisdom — Quotes');
  out = out.replace(/\*\*Project:\*\*[^\n]*\n/g, '');
  out = out.replace(/\*\*Created:\*\*[^\n]*\n/g, '');
  out = out.replace(/\*\*Purpose:\*\*[^\n]*\n/g, '');
  out = out.replace(/\*\*Agent rule:\*\*[^\n]*\n/g, '');
  out = out.replace(/^## How the agent uses this file\r?\n/m, '## When these themes help\n');
  out = out.replace(/\*\*Format in chat:\*\*[^\n]*\n/g, '');
  out = out.replace(/^## Maintenance[\s\S]*$/m, '');
  out = out.replace(/\*\*Related:\*\*[^\n]*\n/g, '');
  out = out.replace(/`buy-decision-workflow\.md`/gi, '');
  out = out.replace(/Quotes lens/gi, 'Quotes');
  out = out.replace(/User doctrine \/ My-agent framework/gi, 'Personal discipline');
  out = out.replace(/\(India Stock Investment Agent\)/gi, '');
  out = out.replace(/\n{3,}/g, '\n\n');
  return out.trim();
}
