/** Strip internal framework sections from markdown shown to end users. */

export function toInvestorFacingReport(markdown: string): string {
  let out = markdown;
  out = out.replace(/^## Framework lens[\s\S]*?(?=^## )/m, '');
  out = out.replace(/^## Context used[\s\S]*?(?=^## )/m, '');
  out = out.replace(
    /\*Generated by Stock Analysis[\s\S]*$/m,
    '*Not investment advice. Framework rules applied in background.*'
  );
  out = out.replace(/\*\*Mode:\*\* Basic Analysis[^\n]*\n/g, '');
  return out.trim();
}
