import fs from 'fs/promises';
import path from 'path';
import { randomUUID } from 'crypto';
import { getUserPaths, assertSafeTenantId } from './tenant';
import { writeTenantIndexFile, writeTenantMarkdownFile } from './tenant-disk-persist';
import { groupByYearMonthDate, type DateYearGroup } from './date-history-group';
import { createClientIfConfigured } from './supabase/server';
import {
  isMissingTableError,
  isSupabaseTableUnavailable,
  markSupabaseTableUnavailable,
  warnMissingTableOnce,
} from './supabase/schema-errors';
import type { MarginAnalysisResult } from './margin-analysis';
import { findFullAnalysisByChildModuleId } from './full-analysis-child-lookup';

export interface MarginAnalysisRecord {
  id: string;
  createdAt: string;
  ticker: string;
  stockName: string;
  sector: string;
  cmp: number | null;
  ebitdaDeltaPp: number | null;
  warningCount: number;
  verdict: string;
  report: string;
  analysis: MarginAnalysisResult;
}

interface MarginIndexFile {
  version: 1;
  entries: MarginAnalysisRecord[];
}

interface MarginHistoryRow {
  id: string;
  user_id: string;
  ticker: string;
  stock_name: string;
  sector: string;
  cmp: number | null;
  ebitda_delta_pp: number | null;
  warning_count: number;
  verdict: string;
  report: string;
  analysis: MarginAnalysisResult;
  created_at: string;
}

const MARGIN_HISTORY_TABLE = 'margin_history';

function marginDir(tenantId: string): string {
  return path.join(getUserPaths(tenantId).portfolioDir, '../stock-calculator/margin');
}

function indexPath(tenantId: string): string {
  return path.join(marginDir(tenantId), 'index.json');
}

async function readIndex(tenantId: string): Promise<MarginIndexFile> {
  try {
    const raw = await fs.readFile(indexPath(tenantId), 'utf8');
    const parsed = JSON.parse(raw) as MarginIndexFile;
    if (parsed?.version === 1 && Array.isArray(parsed.entries)) return parsed;
  } catch {
    /* new */
  }
  return { version: 1, entries: [] };
}

async function writeIndex(tenantId: string, data: MarginIndexFile): Promise<void> {
  await writeTenantIndexFile(indexPath(tenantId), data);
}

export function formatMarginReport(analysis: MarginAnalysisResult): string {
  const lines: string[] = [
    `# Margin Analysis — ${analysis.stockName} (${analysis.ticker})`,
    '',
    `**Sector:** ${analysis.sector}`,
    `**CMP:** ${analysis.cmp != null ? `₹${analysis.cmp.toLocaleString('en-IN')}` : '—'} (${analysis.cmpSource})`,
    `**Data:** ${analysis.dataSource}`,
    `**Verdict:** ${analysis.overallVerdict}`,
    '',
    `> ${analysis.coreQuestion}`,
    '',
    `## ${analysis.partA.title}`,
    '',
    `**Verdict:** ${analysis.partA.verdict}`,
    '',
    '| FY | Gross % | EBITDA % | EBIT % | Net % | Δ pp | Signal | Evidence |',
    '|----|--------:|---------:|-------:|------:|-----:|--------|----------|',
    ...analysis.partA.years.map(
      (y) =>
        `| ${y.fiscalYear} | ${y.grossPct ?? '—'} | ${y.ebitdaPct ?? '—'} | ${y.ebitPct ?? '—'} | ${y.netPct ?? '—'} | ${y.ebitdaDeltaPp ?? '—'} | ${y.signal} | ${y.evidence} |`
    ),
    '',
    `**5Y avg EBITDA:** ${analysis.partA.avgEbitdaPct ?? '—'}% · **Trend:** ${analysis.partA.trendLabel}`,
    '',
    `## ${analysis.partB.title}`,
    '',
    `**Verdict:** ${analysis.partB.verdict}`,
    '',
    '| Metric | Today | 10Y avg | Δ pp | Read | Signal |',
    '|--------|------:|--------:|-----:|------|--------|',
    ...analysis.partB.rows.map(
      (r) =>
        `| ${r.metric} | ${r.todayPct ?? '—'}% | ${r.avg10yPct ?? '—'}% | ${r.deltaPp ?? '—'} | ${r.read} | ${r.signal} |`
    ),
    '',
    `## ${analysis.partC.title}`,
    '',
    analysis.partC.passThroughVerdict,
    '',
  ];

  if (analysis.partC.drivers.length > 0) {
    lines.push(
      '| Driver | Assessment | Impact | Evidence |',
      '|--------|------------|--------|----------|',
      ...analysis.partC.drivers.map(
        (d) => `| ${d.driver} | ${d.assessment} | ${d.impact} | ${d.evidence} |`
      ),
      ''
    );
  }

  if (analysis.partD.quarters.length > 0) {
    lines.push(
      `## ${analysis.partD.title}`,
      '',
      `**Trend:** ${analysis.partD.trendLabel}`,
      '',
      '| Quarter | Revenue (₹ cr) | Margin % |',
      '|---------|---------------:|---------:|',
      ...analysis.partD.quarters.map(
        (q) => `| ${q.quarter} | ${q.revenue ?? '—'} | ${q.marginPct ?? '—'} |`
      ),
      ''
    );
  }

  if (analysis.warnings.length > 0) {
    lines.push('## Warnings', '');
    for (const w of analysis.warnings) {
      lines.push(`- **${w.title}:** ${w.detail}`);
    }
    lines.push('');
  }

  lines.push('---', '', '_Generated by Stock Calculator — Margin Analysis. Not investment advice._');
  return lines.join('\n');
}

export function analysisToRecord(analysis: MarginAnalysisResult, id?: string): MarginAnalysisRecord {
  const recordId = id ?? randomUUID();
  return {
    id: recordId,
    createdAt: new Date().toISOString(),
    ticker: analysis.ticker,
    stockName: analysis.stockName,
    sector: analysis.sector,
    cmp: analysis.cmp,
    ebitdaDeltaPp: analysis.partB.primaryDeltaPp,
    warningCount: analysis.warnings.length,
    verdict: analysis.overallVerdict,
    report: formatMarginReport(analysis),
    analysis,
  };
}

function rowToRecord(row: MarginHistoryRow): MarginAnalysisRecord {
  return {
    id: row.id,
    createdAt: row.created_at,
    ticker: row.ticker,
    stockName: row.stock_name,
    sector: row.sector,
    cmp: row.cmp != null ? Number(row.cmp) : null,
    ebitdaDeltaPp: row.ebitda_delta_pp != null ? Number(row.ebitda_delta_pp) : null,
    warningCount: Number(row.warning_count),
    verdict: row.verdict,
    report: row.report,
    analysis: row.analysis,
  };
}

async function persistRecordToDisk(tenantId: string, record: MarginAnalysisRecord): Promise<void> {
  const index = await readIndex(tenantId);
  const existing = index.entries.findIndex((e) => e.id === record.id);
  if (existing >= 0) index.entries[existing] = record;
  else index.entries.unshift(record);
  await writeIndex(tenantId, index);
  await writeTenantMarkdownFile(
    path.join(marginDir(tenantId), `${record.id}.md`),
    record.report
  );
}

async function fetchAllFromSupabase(userId: string): Promise<MarginAnalysisRecord[]> {
  if (isSupabaseTableUnavailable(MARGIN_HISTORY_TABLE)) return [];
  const supabase = await createClientIfConfigured();
  if (!supabase) return [];

  const { data, error } = await supabase
    .from(MARGIN_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(MARGIN_HISTORY_TABLE);
      warnMissingTableOnce(MARGIN_HISTORY_TABLE, '008_margin_history.sql');
      return [];
    }
    return [];
  }
  return (data as MarginHistoryRow[]).map(rowToRecord);
}

async function fetchOneFromSupabase(userId: string, id: string): Promise<MarginAnalysisRecord | null> {
  if (isSupabaseTableUnavailable(MARGIN_HISTORY_TABLE)) return null;
  const supabase = await createClientIfConfigured();
  if (!supabase) return null;

  const { data, error } = await supabase
    .from(MARGIN_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .eq('id', id)
    .maybeSingle();

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(MARGIN_HISTORY_TABLE);
      warnMissingTableOnce(MARGIN_HISTORY_TABLE, '008_margin_history.sql');
    }
    return null;
  }
  if (!data) return null;
  return rowToRecord(data as MarginHistoryRow);
}

export interface SaveMarginInput {
  tenantId: string;
  userId: string;
  authMode: 'supabase' | 'cookie-dev';
  analysis: MarginAnalysisResult;
}

export async function saveMarginRecord(input: SaveMarginInput): Promise<MarginAnalysisRecord> {
  assertSafeTenantId(input.tenantId);
  const record = analysisToRecord(input.analysis);
  await persistRecordToDisk(input.tenantId, record);

  if (input.authMode === 'supabase') {
    const supabase = await createClientIfConfigured();
    if (supabase && !isSupabaseTableUnavailable(MARGIN_HISTORY_TABLE)) {
      const { error } = await supabase.from(MARGIN_HISTORY_TABLE).insert({
        id: record.id,
        user_id: input.userId,
        ticker: record.ticker,
        stock_name: record.stockName,
        sector: record.sector,
        cmp: record.cmp,
        ebitda_delta_pp: record.ebitdaDeltaPp,
        warning_count: record.warningCount,
        verdict: record.verdict,
        report: record.report,
        analysis: record.analysis,
      });
      if (error && isMissingTableError(error)) {
        markSupabaseTableUnavailable(MARGIN_HISTORY_TABLE);
        warnMissingTableOnce(MARGIN_HISTORY_TABLE, '008_margin_history.sql');
      }
    }
  }
  return record;
}

export async function listMarginRecords(
  tenantId: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<MarginAnalysisRecord[]> {
  assertSafeTenantId(tenantId);
  let entries = (await readIndex(tenantId)).entries;

  if (entries.length === 0 && authMode === 'supabase' && userId) {
    const remote = await fetchAllFromSupabase(userId);
    if (remote.length > 0) {
      for (const record of remote) await persistRecordToDisk(tenantId, record);
      entries = remote;
    }
  }
  return entries.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getMarginRecord(
  tenantId: string,
  id: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<MarginAnalysisRecord | null> {
  const local = (await readIndex(tenantId)).entries.find((e) => e.id === id);
  if (local) return local;

  if (authMode === 'supabase' && userId) {
    const remote = await fetchOneFromSupabase(userId, id);
    if (remote) {
      await persistRecordToDisk(tenantId, remote);
      return remote;
    }
  }

  const full = await findFullAnalysisByChildModuleId(tenantId, id, userId, authMode);
  if (full?.childIds.margin === id) {
    return analysisToRecord(full.analysis.margin, id);
  }

  return null;
}

export function groupMarginByDate(
  entries: MarginAnalysisRecord[]
): DateYearGroup<MarginAnalysisRecord>[] {
  return groupByYearMonthDate(entries, (e) => e.createdAt);
}
