import fs from 'fs/promises';
import path from 'path';
import { randomUUID } from 'crypto';
import { getUserPaths, assertSafeTenantId } from './tenant';
import { writeTenantIndexFile, writeTenantMarkdownFile } from './tenant-disk-persist';
import { groupByYearMonthDate, type DateYearGroup } from './date-history-group';
import { createClientIfConfigured } from './supabase/server';
import {
  isMissingTableError,
  isSupabaseTableUnavailable,
  markSupabaseTableUnavailable,
  warnMissingTableOnce,
} from './supabase/schema-errors';
import type { PegEvaluationResult } from './peg-evaluation';

export interface PegEvaluationRecord {
  id: string;
  createdAt: string;
  ticker: string;
  stockName: string;
  sector: string;
  cmp: number | null;
  pegRatio: number | null;
  totalScore100: number;
  warningCount: number;
  verdict: string;
  report: string;
  analysis: PegEvaluationResult;
}

interface PegIndexFile {
  version: 1;
  entries: PegEvaluationRecord[];
}

interface PegHistoryRow {
  id: string;
  user_id: string;
  ticker: string;
  stock_name: string;
  sector: string;
  cmp: number | null;
  peg_ratio: number | null;
  total_score_100: number;
  warning_count: number;
  verdict: string;
  report: string;
  analysis: PegEvaluationResult;
  created_at: string;
}

const PEG_HISTORY_TABLE = 'peg_history';

function pegDir(tenantId: string): string {
  return path.join(getUserPaths(tenantId).portfolioDir, '../stock-calculator/peg');
}

function indexPath(tenantId: string): string {
  return path.join(pegDir(tenantId), 'index.json');
}

async function readIndex(tenantId: string): Promise<PegIndexFile> {
  try {
    const raw = await fs.readFile(indexPath(tenantId), 'utf8');
    const parsed = JSON.parse(raw) as PegIndexFile;
    if (parsed?.version === 1 && Array.isArray(parsed.entries)) return parsed;
  } catch {
    /* new */
  }
  return { version: 1, entries: [] };
}

async function writeIndex(tenantId: string, data: PegIndexFile): Promise<void> {
  await writeTenantIndexFile(indexPath(tenantId), data);
}

export function formatPegReport(analysis: PegEvaluationResult): string {
  const lines: string[] = [
    `# PEG Evaluation — ${analysis.stockName} (${analysis.ticker})`,
    '',
    `**Sector:** ${analysis.sector}`,
    `**CMP:** ${analysis.cmp != null ? `₹${analysis.cmp.toLocaleString('en-IN')}` : '—'} (${analysis.cmpSource})`,
    `**Score:** ${analysis.totalScore100}/100`,
    `**Verdict:** ${analysis.overallVerdict}`,
    '',
    `> ${analysis.coreQuestion}`,
    '',
    '## Scorecard',
    '',
    '| Parameter | Value | Zone | Indicates |',
    '|-----------|------:|:----:|-----------|',
    ...analysis.scorecard.map(
      (r) => `| ${r.parameter} | ${r.value} | ${r.zone} | ${r.indicates} |`
    ),
    '',
    '## 100-point breakdown',
    '',
    '| Block | Earned | Max |',
    '|-------|-------:|----:|',
    ...analysis.pointsBreakdown.map(
      (p) => `| ${p.label} | ${p.earnedPoints} | ${p.maxPoints} |`
    ),
    '',
  ];

  if (analysis.warnings.length > 0) {
    lines.push('## Warnings', '');
    for (const w of analysis.warnings) {
      lines.push(`- **${w.title}:** ${w.detail}`);
    }
    lines.push('');
  }

  lines.push('---', '', '_Generated by Stock Calculator — PEG Evaluation. Not investment advice._');
  return lines.join('\n');
}

export function analysisToRecord(analysis: PegEvaluationResult, id?: string): PegEvaluationRecord {
  const recordId = id ?? randomUUID();
  return {
    id: recordId,
    createdAt: new Date().toISOString(),
    ticker: analysis.ticker,
    stockName: analysis.stockName,
    sector: analysis.sector,
    cmp: analysis.cmp,
    pegRatio: analysis.pegRatio,
    totalScore100: analysis.totalScore100,
    warningCount: analysis.warnings.length,
    verdict: analysis.overallVerdict,
    report: formatPegReport(analysis),
    analysis,
  };
}

function rowToRecord(row: PegHistoryRow): PegEvaluationRecord {
  return {
    id: row.id,
    createdAt: row.created_at,
    ticker: row.ticker,
    stockName: row.stock_name,
    sector: row.sector,
    cmp: row.cmp != null ? Number(row.cmp) : null,
    pegRatio: row.peg_ratio != null ? Number(row.peg_ratio) : null,
    totalScore100: Number(row.total_score_100),
    warningCount: Number(row.warning_count),
    verdict: row.verdict,
    report: row.report,
    analysis: row.analysis,
  };
}

async function persistRecordToDisk(tenantId: string, record: PegEvaluationRecord): Promise<void> {
  const index = await readIndex(tenantId);
  const existing = index.entries.findIndex((e) => e.id === record.id);
  if (existing >= 0) index.entries[existing] = record;
  else index.entries.unshift(record);
  await writeIndex(tenantId, index);
  await writeTenantMarkdownFile(path.join(pegDir(tenantId), `${record.id}.md`), record.report);
}

async function fetchAllFromSupabase(userId: string): Promise<PegEvaluationRecord[]> {
  if (isSupabaseTableUnavailable(PEG_HISTORY_TABLE)) return [];
  const supabase = await createClientIfConfigured();
  if (!supabase) return [];

  const { data, error } = await supabase
    .from(PEG_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(PEG_HISTORY_TABLE);
      warnMissingTableOnce(PEG_HISTORY_TABLE, '009_peg_history.sql');
      return [];
    }
    return [];
  }
  return (data as PegHistoryRow[]).map(rowToRecord);
}

async function fetchOneFromSupabase(userId: string, id: string): Promise<PegEvaluationRecord | null> {
  if (isSupabaseTableUnavailable(PEG_HISTORY_TABLE)) return null;
  const supabase = await createClientIfConfigured();
  if (!supabase) return null;

  const { data, error } = await supabase
    .from(PEG_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .eq('id', id)
    .maybeSingle();

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(PEG_HISTORY_TABLE);
      warnMissingTableOnce(PEG_HISTORY_TABLE, '009_peg_history.sql');
    }
    return null;
  }
  if (!data) return null;
  return rowToRecord(data as PegHistoryRow);
}

export interface SavePegInput {
  tenantId: string;
  userId: string;
  authMode: 'supabase' | 'cookie-dev';
  analysis: PegEvaluationResult;
}

export async function savePegRecord(input: SavePegInput): Promise<PegEvaluationRecord> {
  assertSafeTenantId(input.tenantId);
  const record = analysisToRecord(input.analysis);
  await persistRecordToDisk(input.tenantId, record);

  if (input.authMode === 'supabase') {
    const supabase = await createClientIfConfigured();
    if (supabase && !isSupabaseTableUnavailable(PEG_HISTORY_TABLE)) {
      const { error } = await supabase.from(PEG_HISTORY_TABLE).insert({
        id: record.id,
        user_id: input.userId,
        ticker: record.ticker,
        stock_name: record.stockName,
        sector: record.sector,
        cmp: record.cmp,
        peg_ratio: record.pegRatio,
        total_score_100: record.totalScore100,
        warning_count: record.warningCount,
        verdict: record.verdict,
        report: record.report,
        analysis: record.analysis,
      });
      if (error && isMissingTableError(error)) {
        markSupabaseTableUnavailable(PEG_HISTORY_TABLE);
        warnMissingTableOnce(PEG_HISTORY_TABLE, '009_peg_history.sql');
      }
    }
  }
  return record;
}

export async function listPegRecords(
  tenantId: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<PegEvaluationRecord[]> {
  assertSafeTenantId(tenantId);
  let entries = (await readIndex(tenantId)).entries;

  if (entries.length === 0 && authMode === 'supabase' && userId) {
    const remote = await fetchAllFromSupabase(userId);
    if (remote.length > 0) {
      for (const record of remote) await persistRecordToDisk(tenantId, record);
      entries = remote;
    }
  }
  return entries.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getPegRecord(
  tenantId: string,
  id: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<PegEvaluationRecord | null> {
  const local = (await readIndex(tenantId)).entries.find((e) => e.id === id);
  if (local) return local;

  if (authMode === 'supabase' && userId) {
    const remote = await fetchOneFromSupabase(userId, id);
    if (remote) {
      await persistRecordToDisk(tenantId, remote);
      return remote;
    }
  }
  return null;
}

export function groupPegByDate(
  entries: PegEvaluationRecord[]
): DateYearGroup<PegEvaluationRecord>[] {
  return groupByYearMonthDate(entries, (e) => e.createdAt);
}
