import fs from 'fs/promises';
import path from 'path';
import { randomUUID } from 'crypto';
import { getUserPaths, assertSafeTenantId } from './tenant';
import { writeTenantIndexFile, writeTenantMarkdownFile } from './tenant-disk-persist';
import { isServerlessReadOnlyFs } from './serverless-fs';
import { groupByYearMonthDate, type DateYearGroup } from './date-history-group';
import { createClientIfConfigured } from './supabase/server';
import {
  isMissingTableError,
  isSupabaseTableUnavailable,
  markSupabaseTableUnavailable,
  warnMissingTableOnce,
} from './supabase/schema-errors';
import type { StockCalculatorFullResult } from './stock-calculator-full';
import { saveCalculatorRecord } from './stock-calculator-history';
import { savePeEvaluationRecord } from './pe-evaluation-history';
import { saveEarningsQualityRecord } from './earnings-quality-history';
import { saveMarginRecord } from './margin-history';
import { saveBusinessQualityRecord } from './business-quality-history';
import { saveRiskDecisionRecord } from './risk-decision-history';

export interface FullAnalysisChildIds {
  cagr: string;
  pe: string | null;
  earningsQuality: string;
  margin: string;
  businessQuality: string;
  riskDecision: string;
}

export interface StockCalculatorFullRecord {
  id: string;
  createdAt: string;
  ticker: string;
  stockName: string;
  sector: string;
  cmp: number | null;
  expectedCagrPct: number;
  years: number;
  overviewVerdict: string;
  childIds: FullAnalysisChildIds;
  report: string;
  analysis: StockCalculatorFullResult;
}

interface FullIndexFile {
  version: 1;
  entries: StockCalculatorFullRecord[];
}

interface FullHistoryRow {
  id: string;
  user_id: string;
  ticker: string;
  stock_name: string;
  sector: string;
  cmp: number | null;
  expected_cagr_pct: number;
  years: number;
  overview_verdict: string;
  child_ids: FullAnalysisChildIds;
  report: string;
  analysis: StockCalculatorFullResult;
  created_at: string;
}

const FULL_HISTORY_TABLE = 'stock_calculator_full_history';

function fullDir(tenantId: string): string {
  return path.join(getUserPaths(tenantId).portfolioDir, '../stock-calculator/full');
}

function indexPath(tenantId: string): string {
  return path.join(fullDir(tenantId), 'index.json');
}

async function readIndex(tenantId: string): Promise<FullIndexFile> {
  try {
    const raw = await fs.readFile(indexPath(tenantId), 'utf8');
    const parsed = JSON.parse(raw) as FullIndexFile;
    if (parsed?.version === 1 && Array.isArray(parsed.entries)) return parsed;
  } catch {
    /* new */
  }
  return { version: 1, entries: [] };
}

async function writeIndex(tenantId: string, data: FullIndexFile): Promise<void> {
  await writeTenantIndexFile(indexPath(tenantId), data);
}

export function formatFullAnalysisReport(analysis: StockCalculatorFullResult): string {
  const lines = [
    `# Full Stock Analysis — ${analysis.stockName} (${analysis.ticker})`,
    '',
    `**Sector:** ${analysis.sector}`,
    `**CAGR inputs:** ${analysis.inputs.expectedCagrPct}% · ${analysis.inputs.years}Y · ${analysis.inputs.peBasis.toUpperCase()} P/E`,
    '',
    '## Overview',
    '',
    '| Module | Verdict |',
    '|--------|---------|',
    `| CAGR Evaluation | ${analysis.overview.cagrVerdict} |`,
    `| PE Evaluation | ${analysis.overview.peVerdict} |`,
    `| Earnings Quality | ${analysis.overview.earningsQualityVerdict} |`,
    `| Margin Analysis | ${analysis.overview.marginVerdict} |`,
    `| Business Quality | ${analysis.overview.businessQualityVerdict} |`,
    `| Risk & Decision | ${analysis.overview.riskVerdict} |`,
    '',
    '---',
    '',
    '_Generated by Stock Calculator — Full Analysis. Not investment advice._',
  ];
  return lines.join('\n');
}

export interface SaveFullAnalysisInput {
  tenantId: string;
  userId: string;
  authMode: 'supabase' | 'cookie-dev';
  analysis: StockCalculatorFullResult;
  /** Re-run and replace this saved record (same URL / id). */
  refreshRecordId?: string;
}

export interface SavedFullAnalysisOutcome {
  record: StockCalculatorFullRecord;
  persisted: boolean;
}

function mergeFullRecords(
  disk: StockCalculatorFullRecord[],
  remote: StockCalculatorFullRecord[]
): StockCalculatorFullRecord[] {
  const byId = new Map<string, StockCalculatorFullRecord>();
  for (const e of [...disk, ...remote]) {
    const prev = byId.get(e.id);
    if (!prev || e.createdAt.localeCompare(prev.createdAt) > 0) {
      byId.set(e.id, e);
    }
  }
  return [...byId.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

async function listFromSupabase(userId: string): Promise<StockCalculatorFullRecord[]> {
  if (isSupabaseTableUnavailable(FULL_HISTORY_TABLE)) return [];
  const supabase = await createClientIfConfigured();
  if (!supabase) return [];

  const { data, error } = await supabase
    .from(FULL_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(300);

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(FULL_HISTORY_TABLE);
      warnMissingTableOnce(FULL_HISTORY_TABLE, '009_stock_calculator_full_history.sql');
    }
    return [];
  }
  return (data ?? []).map((row) => rowToRecord(row as FullHistoryRow));
}

export async function saveFullAnalysisRecord(
  input: SaveFullAnalysisInput
): Promise<SavedFullAnalysisOutcome> {
  assertSafeTenantId(input.tenantId);
  const { analysis } = input;

  let recordId = input.refreshRecordId ?? randomUUID();
  if (input.refreshRecordId) {
    const existing = await getFullAnalysisRecord(
      input.tenantId,
      input.refreshRecordId,
      input.userId,
      input.authMode
    );
    if (!existing || existing.ticker !== analysis.ticker) {
      recordId = randomUUID();
    }
  }

  const [cagrRec, eqRec, marginRec, bqRec, riskRec, peRec] = await Promise.all([
    saveCalculatorRecord({
      tenantId: input.tenantId,
      userId: input.userId,
      authMode: input.authMode,
      result: analysis.cagr,
    }),
    saveEarningsQualityRecord({
      tenantId: input.tenantId,
      userId: input.userId,
      authMode: input.authMode,
      analysis: analysis.earningsQuality,
    }),
    saveMarginRecord({
      tenantId: input.tenantId,
      userId: input.userId,
      authMode: input.authMode,
      analysis: analysis.margin,
    }),
    saveBusinessQualityRecord({
      tenantId: input.tenantId,
      userId: input.userId,
      authMode: input.authMode,
      analysis: analysis.businessQuality,
    }),
    saveRiskDecisionRecord({
      tenantId: input.tenantId,
      userId: input.userId,
      authMode: input.authMode,
      analysis: analysis.riskDecision,
    }),
    analysis.peScorecard
      ? savePeEvaluationRecord({
          tenantId: input.tenantId,
          userId: input.userId,
          authMode: input.authMode,
          scorecard: analysis.peScorecard,
        })
      : Promise.resolve(null),
  ]);

  const record: StockCalculatorFullRecord = {
    id: recordId,
    createdAt: new Date().toISOString(),
    ticker: analysis.ticker,
    stockName: analysis.stockName,
    sector: analysis.sector,
    cmp: analysis.cagr.snapshot.cmp,
    expectedCagrPct: analysis.inputs.expectedCagrPct,
    years: analysis.inputs.years,
    overviewVerdict: analysis.overview.cagrVerdict,
    childIds: {
      cagr: cagrRec.id,
      pe: peRec?.id ?? null,
      earningsQuality: eqRec.id,
      margin: marginRec.id,
      businessQuality: bqRec.id,
      riskDecision: riskRec.id,
    },
    report: formatFullAnalysisReport(analysis),
    analysis,
  };

  let persisted = false;

  const index = await readIndex(input.tenantId);
  const existingIdx = index.entries.findIndex((e) => e.id === record.id);
  if (existingIdx >= 0) index.entries[existingIdx] = record;
  else index.entries.unshift(record);
  await writeIndex(input.tenantId, index);
  if (!isServerlessReadOnlyFs()) persisted = true;

  await writeTenantMarkdownFile(
    path.join(fullDir(input.tenantId), `${record.id}.md`),
    record.report
  );

  if (input.authMode === 'supabase') {
    const supabase = await createClientIfConfigured();
    if (supabase && !isSupabaseTableUnavailable(FULL_HISTORY_TABLE)) {
      const row = {
        id: record.id,
        user_id: input.userId,
        ticker: record.ticker,
        stock_name: record.stockName,
        sector: record.sector,
        cmp: record.cmp,
        expected_cagr_pct: record.expectedCagrPct,
        years: record.years,
        overview_verdict: record.overviewVerdict,
        child_ids: record.childIds,
        report: record.report,
        analysis: record.analysis,
        created_at: record.createdAt,
      };

      const isRefresh = Boolean(input.refreshRecordId && input.refreshRecordId === record.id);
      const { error } = isRefresh
        ? await supabase.from(FULL_HISTORY_TABLE).update(row).eq('id', record.id).eq('user_id', input.userId)
        : await supabase.from(FULL_HISTORY_TABLE).insert(row);

      if (error && isMissingTableError(error)) {
        markSupabaseTableUnavailable(FULL_HISTORY_TABLE);
        warnMissingTableOnce(FULL_HISTORY_TABLE, '009_stock_calculator_full_history.sql');
      } else if (!error) {
        persisted = true;
      }
    }
  }

  return { record, persisted };
}

function rowToRecord(row: FullHistoryRow): StockCalculatorFullRecord {
  return {
    id: row.id,
    createdAt: row.created_at,
    ticker: row.ticker,
    stockName: row.stock_name,
    sector: row.sector,
    cmp: row.cmp != null ? Number(row.cmp) : null,
    expectedCagrPct: Number(row.expected_cagr_pct),
    years: Number(row.years),
    overviewVerdict: row.overview_verdict,
    childIds: row.child_ids,
    report: row.report,
    analysis: row.analysis,
  };
}

async function persistRecordToDisk(tenantId: string, record: StockCalculatorFullRecord): Promise<void> {
  const index = await readIndex(tenantId);
  const i = index.entries.findIndex((e) => e.id === record.id);
  if (i >= 0) index.entries[i] = record;
  else index.entries.unshift(record);
  await writeIndex(tenantId, index);
  await writeTenantMarkdownFile(
    path.join(fullDir(tenantId), `${record.id}.md`),
    record.report
  );
}

async function fetchOneFromSupabase(
  userId: string,
  id: string
): Promise<StockCalculatorFullRecord | null> {
  if (isSupabaseTableUnavailable(FULL_HISTORY_TABLE)) return null;
  const supabase = await createClientIfConfigured();
  if (!supabase) return null;

  const { data, error } = await supabase
    .from(FULL_HISTORY_TABLE)
    .select('*')
    .eq('user_id', userId)
    .eq('id', id)
    .maybeSingle();

  if (error) {
    if (isMissingTableError(error)) {
      markSupabaseTableUnavailable(FULL_HISTORY_TABLE);
      warnMissingTableOnce(FULL_HISTORY_TABLE, '009_stock_calculator_full_history.sql');
    }
    return null;
  }
  if (!data) return null;
  return rowToRecord(data as FullHistoryRow);
}

export async function listFullAnalysisRecords(
  tenantId: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<StockCalculatorFullRecord[]> {
  assertSafeTenantId(tenantId);
  const disk = (await readIndex(tenantId)).entries;

  if (authMode === 'supabase' && userId) {
    const remote = await listFromSupabase(userId);
    if (remote.length > 0 || isServerlessReadOnlyFs()) {
      return mergeFullRecords(disk, remote);
    }
  }

  return disk.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/** Latest saved full analysis for one ticker (this user). */
export async function getLatestFullAnalysisByTicker(
  tenantId: string,
  ticker: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<StockCalculatorFullRecord | null> {
  const key = ticker.trim().toUpperCase();
  const all = await listFullAnalysisRecords(tenantId, userId, authMode);
  return all.find((e) => e.ticker.toUpperCase() === key) ?? null;
}

export async function getFullAnalysisRecord(
  tenantId: string,
  id: string,
  userId?: string,
  authMode?: 'supabase' | 'cookie-dev'
): Promise<StockCalculatorFullRecord | null> {
  const local = (await readIndex(tenantId)).entries.find((e) => e.id === id);
  if (local) return local;

  if (authMode === 'supabase' && userId) {
    const remote = await fetchOneFromSupabase(userId, id);
    if (remote) {
      await persistRecordToDisk(tenantId, remote);
      return remote;
    }
  }
  return null;
}

export function groupFullAnalysisByDate(
  entries: StockCalculatorFullRecord[]
): DateYearGroup<StockCalculatorFullRecord>[] {
  return groupByYearMonthDate(entries, (e) => e.createdAt);
}
