/**
 * Bundle repo markdown into web/lib/bundled/*.generated.ts for Vercel/serverless.
 * Run: npm run sync-bundled-docs (also runs before build).
 */
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { GLOSSARY_PATH, listAllDocs } from '../lib/documentation-index';
import { SECTOR_OUTLOOK_PATHS } from '../lib/sector-slugs';

const webDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.join(webDir, '..');
const bundledDir = path.join(webDir, 'lib/bundled');

async function writeGeneratedTs(filename: string, exportName: string, value: unknown): Promise<void> {
  await fs.mkdir(bundledDir, { recursive: true });
  const file = path.join(bundledDir, filename);
  await fs.writeFile(
    file,
    `/** Auto-generated by sync-bundled-docs — do not edit */\nexport const ${exportName} = ${JSON.stringify(value)} as const;\n`,
    'utf8'
  );
}

async function readTextIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch {
    return null;
  }
}

async function walkDir(root: string, visit: (filePath: string, name: string) => Promise<void>): Promise<void> {
  let entries;
  try {
    entries = await fs.readdir(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const full = path.join(root, e.name);
    if (e.isDirectory()) await walkDir(full, visit);
    else await visit(full, e.name);
  }
}

async function scanStockbookTickerIndex(): Promise<
  Record<string, { sector: string; stock: string; ticker: string }>
> {
  const stockBook = path.join(repoRoot, 'StockBook');
  const out: Record<string, { sector: string; stock: string; ticker: string }> = {};

  await walkDir(stockBook, async (filePath, name) => {
    const rel = path.relative(stockBook, filePath);
    const parts = rel.split(path.sep);
    if (parts.length < 3) return;
    const sector = parts[0];
    const stock = parts[1];

    if (name === 'summary-analysis.md') {
      const md = await readTextIfExists(filePath);
      if (!md) return;
      const match = md.match(/\*\*Ticker:\*\*\s*([A-Z0-9.&-]+)/i);
      if (!match) return;
      const ticker = match[1].toUpperCase();
      out[ticker] = { sector, stock, ticker };
      return;
    }

    const paramMatch = name.match(/^PARAMETERS_([A-Z0-9.&-]+)\.md$/i);
    if (paramMatch) {
      const ticker = paramMatch[1].toUpperCase();
      if (!out[ticker]) out[ticker] = { sector, stock, ticker };
    }
  });

  return out;
}

async function scanStockBookTickerFiles(
  pattern: RegExp,
  tickerFromName: (name: string) => string | null
): Promise<Record<string, string>> {
  const stockBook = path.join(repoRoot, 'StockBook');
  const out: Record<string, string> = {};
  await walkDir(stockBook, async (filePath, name) => {
    if (!pattern.test(name)) return;
    const ticker = tickerFromName(name);
    if (!ticker) return;
    const md = await readTextIfExists(filePath);
    if (md) out[ticker.toUpperCase()] = md;
  });
  return out;
}

async function scanNewsSummaries(): Promise<Record<string, string>> {
  const newsRoot = path.join(repoRoot, 'News');
  const out: Record<string, string> = {};

  let monthDirs;
  try {
    monthDirs = await fs.readdir(newsRoot, { withFileTypes: true });
  } catch {
    return out;
  }

  for (const monthDir of monthDirs) {
    if (!monthDir.isDirectory() || !/^\d{4}-\d{2}$/.test(monthDir.name)) continue;
    const monthPath = path.join(newsRoot, monthDir.name);
    const dayDirs = await fs.readdir(monthPath, { withFileTypes: true });

    for (const dayDir of dayDirs) {
      if (!dayDir.isDirectory()) continue;
      if (!/^\d{4}-\d{2}-\d{2}$/.test(dayDir.name)) continue;
      const summaryPath = path.join(monthPath, dayDir.name, 'summary.md');
      const md = await readTextIfExists(summaryPath);
      if (md) out[dayDir.name] = md;
    }
  }

  return out;
}

async function main() {
  let ok = 0;
  let miss = 0;

  const docBySlug: Record<string, string> = {};
  for (const doc of listAllDocs()) {
    const src = path.join(repoRoot, doc.path.replace(/\//g, path.sep));
    const md = await readTextIfExists(src);
    if (md) {
      docBySlug[doc.slug] = md;
      ok += 1;
    } else {
      miss += 1;
      console.warn(`[sync-bundled-docs] missing: ${doc.path}`);
    }
  }
  await writeGeneratedTs('docs.generated.ts', 'DOC_MARKDOWN_BY_SLUG', docBySlug);

  const glossaryMd = await readTextIfExists(path.join(repoRoot, GLOSSARY_PATH));
  if (glossaryMd) {
    await writeGeneratedTs('glossary.generated.ts', 'GLOSSARY_MARKDOWN', glossaryMd);
    ok += 1;
  } else {
    miss += 1;
    console.warn(`[sync-bundled-docs] missing: ${GLOSSARY_PATH}`);
  }

  const quotesMd = await readTextIfExists(path.join(repoRoot, 'investor-wisdom/quotes.md'));
  if (quotesMd) {
    await writeGeneratedTs('wisdom-quotes.generated.ts', 'WISDOM_QUOTES_MARKDOWN', quotesMd);
    ok += 1;
  } else {
    miss += 1;
    console.warn('[sync-bundled-docs] missing: investor-wisdom/quotes.md');
  }

  const newsByDate = await scanNewsSummaries();
  await writeGeneratedTs('news-summaries.generated.ts', 'NEWS_SUMMARIES_BY_DATE', newsByDate);
  ok += Object.keys(newsByDate).length;

  const parametersByTicker = await scanStockBookTickerFiles(/^PARAMETERS_[A-Z0-9.&-]+\.md$/i, (name) => {
    const m = name.match(/^PARAMETERS_([A-Z0-9.&-]+)\.md$/i);
    return m?.[1] ?? null;
  });
  const pegByTicker = await scanStockBookTickerFiles(/^PEG_[A-Z0-9.&-]+\.md$/i, (name) => {
    const m = name.match(/^PEG_([A-Z0-9.&-]+)\.md$/i);
    return m?.[1] ?? null;
  });
  const marginByTicker = await scanStockBookTickerFiles(/^MARGIN_[A-Z0-9.&-]+\.md$/i, (name) => {
    const m = name.match(/^MARGIN_([A-Z0-9.&-]+)\.md$/i);
    return m?.[1] ?? null;
  });
  const earningsQualityByTicker = await scanStockBookTickerFiles(
    /^EARNINGS_QUALITY_[A-Z0-9.&-]+\.md$/i,
    (name) => {
      const m = name.match(/^EARNINGS_QUALITY_([A-Z0-9.&-]+)\.md$/i);
      return m?.[1] ?? null;
    }
  );
  await fs.writeFile(
    path.join(bundledDir, 'stockbook-parameters.generated.ts'),
    `/** Auto-generated by sync-bundled-docs — do not edit */\nexport const PARAMETERS_MD_BY_TICKER = ${JSON.stringify(parametersByTicker)} as const;\nexport const PEG_MD_BY_TICKER = ${JSON.stringify(pegByTicker)} as const;\nexport const MARGIN_MD_BY_TICKER = ${JSON.stringify(marginByTicker)} as const;\nexport const EARNINGS_QUALITY_MD_BY_TICKER = ${JSON.stringify(earningsQualityByTicker)} as const;\n`,
    'utf8'
  );
  ok +=
    Object.keys(parametersByTicker).length +
    Object.keys(pegByTicker).length +
    Object.keys(marginByTicker).length +
    Object.keys(earningsQualityByTicker).length;

  const sectorOutlookByPath: Record<string, string> = {};
  for (const relPath of Object.values(SECTOR_OUTLOOK_PATHS)) {
    const src = path.join(repoRoot, relPath.replace(/\//g, path.sep));
    const md = await readTextIfExists(src);
    if (md) sectorOutlookByPath[relPath] = md;
    else {
      miss += 1;
      console.warn(`[sync-bundled-docs] missing sector outlook: ${relPath}`);
    }
  }
  ok += Object.keys(sectorOutlookByPath).length;

  const comparativeRankByPath: Record<string, string> = {};
  await walkDir(path.join(repoRoot, 'StockBook'), async (filePath, name) => {
    if (!name.endsWith('-comparative-rank.md')) return;
    const rel = path
      .relative(path.join(repoRoot, 'StockBook'), filePath)
      .split(path.sep)
      .join('/');
    const key = `StockBook/${rel}`;
    const md = await readTextIfExists(filePath);
    if (md) comparativeRankByPath[key] = md;
  });
  await fs.writeFile(
    path.join(bundledDir, 'sector-outlook.generated.ts'),
    `/** Auto-generated by sync-bundled-docs — do not edit */\nexport const SECTOR_OUTLOOK_MD_BY_PATH = ${JSON.stringify(sectorOutlookByPath)} as const;\nexport const COMPARATIVE_RANK_MD_BY_PATH = ${JSON.stringify(comparativeRankByPath)} as const;\n`,
    'utf8'
  );
  ok += Object.keys(comparativeRankByPath).length;

  const stockbookIndex = await scanStockbookTickerIndex();

  const summaryByTicker: Record<string, string> = {};
  const faqByTicker: Record<string, string> = {};
  const approachByTicker: Record<string, string> = {};
  const clipStockbook = (md: string, max = 12000) =>
    md.length <= max ? md : md.slice(0, max) + '\n\n… [truncated at sync]';

  await walkDir(path.join(repoRoot, 'StockBook'), async (filePath, name) => {
    const rel = path.relative(path.join(repoRoot, 'StockBook'), filePath);
    const parts = rel.split(path.sep);
    if (parts.length < 3) return;
    const md = await readTextIfExists(filePath);
    if (!md) return;

    let ticker: string | null = null;
    const fromSummary = md.match(/\*\*Ticker:\*\*\s*([A-Z0-9.&-]+)/i);
    if (fromSummary) ticker = fromSummary[1].toUpperCase();

    if (!ticker) {
      const paramInFolder = name.match(/^PARAMETERS_([A-Z0-9.&-]+)\.md$/i);
      if (paramInFolder) ticker = paramInFolder[1].toUpperCase();
    }

    if (!ticker && stockbookIndex) {
      for (const [t, loc] of Object.entries(stockbookIndex)) {
        if (loc.sector === parts[0] && loc.stock === parts[1]) {
          ticker = t;
          break;
        }
      }
    }

    if (!ticker) return;

    if (name === 'summary-analysis.md') {
      summaryByTicker[ticker] = clipStockbook(md);
    } else if (name === 'faq.md') {
      faqByTicker[ticker] = clipStockbook(md, 8000);
    } else if (name === 'suggested-approach.md') {
      approachByTicker[ticker] = clipStockbook(md, 8000);
    }
  });

  await fs.writeFile(
    path.join(bundledDir, 'stockbook-tabs.generated.ts'),
    `/** Auto-generated by sync-bundled-docs — do not edit */\nexport const SUMMARY_MD_BY_TICKER = ${JSON.stringify(summaryByTicker)} as const;\nexport const FAQ_MD_BY_TICKER = ${JSON.stringify(faqByTicker)} as const;\nexport const APPROACH_MD_BY_TICKER = ${JSON.stringify(approachByTicker)} as const;\n`,
    'utf8'
  );
  ok +=
    Object.keys(summaryByTicker).length +
    Object.keys(faqByTicker).length +
    Object.keys(approachByTicker).length;

  await writeGeneratedTs('stockbook-index.generated.ts', 'STOCKBOOK_TICKER_INDEX', stockbookIndex);
  ok += Object.keys(stockbookIndex).length;

  console.log(
    `[sync-bundled-docs] generated docs (${Object.keys(docBySlug).length}), glossary, wisdom, news (${Object.keys(newsByDate).length} days), PARAMETERS (${Object.keys(parametersByTicker).length}), PEG (${Object.keys(pegByTicker).length}), sector outlooks (${Object.keys(sectorOutlookByPath).length}), comparative ranks (${Object.keys(comparativeRankByPath).length}), StockBook tabs (summary ${Object.keys(summaryByTicker).length}, faq ${Object.keys(faqByTicker).length}), tickers (${Object.keys(stockbookIndex).length}); ${miss} missing source file(s)`
  );
  if (miss > 0) process.exitCode = 0;
}

main();
