/**
 * Bundle repo markdown into web/lib/bundled/*.generated.ts for Vercel/serverless.
 * Run: npm run sync-bundled-docs (also runs before build).
 */
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { GLOSSARY_PATH, listAllDocs } from '../lib/documentation-index';

const webDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.join(webDir, '..');
const bundledDir = path.join(webDir, 'lib/bundled');

async function writeGeneratedTs(filename: string, exportName: string, value: unknown): Promise<void> {
  await fs.mkdir(bundledDir, { recursive: true });
  const file = path.join(bundledDir, filename);
  await fs.writeFile(
    file,
    `/** Auto-generated by sync-bundled-docs — do not edit */\nexport const ${exportName} = ${JSON.stringify(value)} as const;\n`,
    'utf8'
  );
}

async function readTextIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch {
    return null;
  }
}

async function scanNewsSummaries(): Promise<Record<string, string>> {
  const newsRoot = path.join(repoRoot, 'News');
  const out: Record<string, string> = {};

  let monthDirs;
  try {
    monthDirs = await fs.readdir(newsRoot, { withFileTypes: true });
  } catch {
    return out;
  }

  for (const monthDir of monthDirs) {
    if (!monthDir.isDirectory() || !/^\d{4}-\d{2}$/.test(monthDir.name)) continue;
    const monthPath = path.join(newsRoot, monthDir.name);
    const dayDirs = await fs.readdir(monthPath, { withFileTypes: true });

    for (const dayDir of dayDirs) {
      if (!dayDir.isDirectory()) continue;
      if (!/^\d{4}-\d{2}-\d{2}$/.test(dayDir.name)) continue;
      const summaryPath = path.join(monthPath, dayDir.name, 'summary.md');
      const md = await readTextIfExists(summaryPath);
      if (md) out[dayDir.name] = md;
    }
  }

  return out;
}

async function main() {
  let ok = 0;
  let miss = 0;

  const docBySlug: Record<string, string> = {};
  for (const doc of listAllDocs()) {
    const src = path.join(repoRoot, doc.path.replace(/\//g, path.sep));
    const md = await readTextIfExists(src);
    if (md) {
      docBySlug[doc.slug] = md;
      ok += 1;
    } else {
      miss += 1;
      console.warn(`[sync-bundled-docs] missing: ${doc.path}`);
    }
  }
  await writeGeneratedTs('docs.generated.ts', 'DOC_MARKDOWN_BY_SLUG', docBySlug);

  const glossaryMd = await readTextIfExists(path.join(repoRoot, GLOSSARY_PATH));
  if (glossaryMd) {
    await writeGeneratedTs('glossary.generated.ts', 'GLOSSARY_MARKDOWN', glossaryMd);
    ok += 1;
  } else {
    miss += 1;
    console.warn(`[sync-bundled-docs] missing: ${GLOSSARY_PATH}`);
  }

  const quotesMd = await readTextIfExists(path.join(repoRoot, 'investor-wisdom/quotes.md'));
  if (quotesMd) {
    await writeGeneratedTs('wisdom-quotes.generated.ts', 'WISDOM_QUOTES_MARKDOWN', quotesMd);
    ok += 1;
  } else {
    miss += 1;
    console.warn('[sync-bundled-docs] missing: investor-wisdom/quotes.md');
  }

  const newsByDate = await scanNewsSummaries();
  await writeGeneratedTs('news-summaries.generated.ts', 'NEWS_SUMMARIES_BY_DATE', newsByDate);
  ok += Object.keys(newsByDate).length;

  console.log(
    `[sync-bundled-docs] generated docs (${Object.keys(docBySlug).length}), glossary, wisdom, news (${Object.keys(newsByDate).length} days); ${miss} missing source file(s)`
  );
  if (miss > 0) process.exitCode = 0;
}

main();
